# Generated by Django 4.2.24 on 2025-09-21 03:40

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_title',
            field=models.CharField(blank=True, help_text='Título principal de la página', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sections',
            field=wagtail.fields.StreamField([('section', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título de la sección', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Contenido de la sección', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 1)]], {})}),
        ),
    ]
