# Generated by Django 4.2.24 on 2025-09-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0003_explorepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
