# Generated by Django 4.2.24 on 2025-09-26 04:10

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='dashboard_blocks',
            field=wagtail.fields.StreamField([('block', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Título de la sección', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Contenido de la sección', 'required': True}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enlace opcional', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1), ('link', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
