# Generated by Django 4.2.24 on 2025-09-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('Interfaz', '0005_homepage_dashboard_blocks_alter_homepage_intro_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExplorePage',
            new_name='CalendarioPage',
        ),
    ]
