# Generated by Django 5.2.6 on 2025-10-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0007_cronometropage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronometropage',
            name='tiempo_cronometro',
        ),
        migrations.AddField(
            model_name='cronometropage',
            name='tiempo_descanso',
            field=models.TimeField(blank=True, help_text='Tiempo de descanso', null=True),
        ),
        migrations.AddField(
            model_name='cronometropage',
            name='tiempo_estudio',
            field=models.TimeField(blank=True, help_text='Tiempo de estudio', null=True),
        ),
    ]
