# Generated by Django 5.2.6 on 2025-10-02 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0008_remove_cronometropage_tiempo_cronometro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronometropage',
            name='tiempo_descanso',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=600), help_text='Tiempo de descanso', null=True),
        ),
        migrations.AlterField(
            model_name='cronometropage',
            name='tiempo_estudio',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3000), help_text='Tiempo de estudio', null=True),
        ),
    ]
