# Generated by Django 5.2.7 on 2025-10-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interfaz', '0009_alter_cronometropage_tiempo_descanso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
    ]
